addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.3.4")
addSbtPlugin("io.get-coursier"  % "sbt-coursier"        % "1.0.3")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.0")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.12")
